CREATE DATABASE ProyectoIndra;
USE ProyectoIndra;

-- 1. USUARIO
CREATE TABLE USUARIO (
    ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100),
    email VARCHAR(255) NOT NULL UNIQUE,
    contraseña VARCHAR(255) NOT NULL
);

-- 2. CATEGORIA
CREATE TABLE CATEGORIA (
    ID_CATEGORIA INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100),
    descripcion VARCHAR(330)
);

-- 3. UBICACION
CREATE TABLE UBICACION (
    ID_UBICACION INT AUTO_INCREMENT PRIMARY KEY,
    tipo ENUM('presencial', 'virtual', 'híbrido') NOT NULL,
    direccion VARCHAR(245),
    enlace VARCHAR(500)
);

-- 4. EVENTOS 
CREATE TABLE EVENTOS (
    ID_EVENTOS INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100),
    fecha DATE,
    duracion INT,
    ID_UBICACION INT,
    ID_CATEGORIA INT,
    estado ENUM('Publicado', 'Cancelado', 'Finalizado'),
    FOREIGN KEY (ID_UBICACION) REFERENCES UBICACION(ID_UBICACION),
    FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA)
);

-- 5. INSCRIPCION (
CREATE TABLE INSCRIPCION (
    ID_INSCRIPCION INT AUTO_INCREMENT PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    ID_EVENTO INT NOT NULL,
    estado ENUM('pendiente', 'confirmada', 'cancelada', 'rechazada', 'asistió', 'ausente') NOT NULL DEFAULT 'pendiente',
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    FOREIGN KEY (ID_EVENTO) REFERENCES EVENTOS(ID_EVENTOS)
);

-- 6. ORGANIZADOR (ajustado también)
CREATE TABLE ORGANIZADOR (
    ID_ORGANIZADOR INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(225),
    email_profesional VARCHAR(225) NOT NULL UNIQUE,
    telefono_contacto VARCHAR(20)
);






